export const distritos =
  [
    "Ate",
    "Barranco",
    "Breña",
    "Cercado de Lima",
    "Chorrillos",
    "Comas",
    "El Agustino",
    "Independencia",
    "Jesus Maria",
    "La Molina",
    "La Victoria",
    "Lince",
    "Los Olivos",
    "Magdalena del Mar",
    "Miraflores",
    "Pueblo Libre",
    "Puente Piedra",
    "Rimac",
    "San Borja",
    "San Isidro",
    "San Juan de Lurigancho",
    "San Luis",
    "San Martin de Porres",
    "San Miguel",
    "Santa Anita",
    "Santa Rosa",
    "Santiago de Surco",
    "Surquillo",
    "Villa El Salvador",
    "Villa Maria del Triunfo"
  ];
